---
# tasks file for common
- name: Update aptcache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install WP dependencies
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - mysql-server
